<a href="https://colab.research.google.com/github/shiv9956/AIML-summer-internship-2026/blob/main/numpy-pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello")
"""this is
a multiline
comment"""
'''
this is
a multiline
comment
'''

hello

'\nthis is\na multiline \ncomment\n'

In [ ]:
name="huj"
age=22
college="srmcem"
print(f"{name}\n{age}\n{college}")

huj
22
srmcem

In [ ]:
a,b=10,20
print(f"original a={a} and b={b}")
a,b=b,a
print(f"after swap a={a} and b={b}")

original a=10 and b=20
after swap a=20 and b=10

In [ ]:
print(type(1.24))
print(type(int(1.24)))

<class 'float'>
<class 'int'>

In [ ]:
name=input("enter your name :")
age=int(input("enter your age :"))
college=input("enter your college :")
print(f"{name}\n{age}\n{college}")

enter your name :huj
enter your age :22
enter your college :srm
huj
22
srm

In [ ]:
a,b=10,20
print(f"a+b={a+b}")
print(f"a-b={a-b}")
print(f"a*b={a*b}")
print(f"a/b={a/b}")
print(f"a//b={a//b}")
print(f"a%b={a%b}")
print(f"a**b={a**b}")

a+b=30
a-b=-10
a*b=200
a/b=0.5
a//b=0
a%b=10
a**b=100000000000000000000

In [ ]:
age=19
print("you are eligible to vote") if age >= 18 else print("your are not eligible to vote")

you are eligible to vote

In [ ]:
age=19
print("you are eligible to be a member of parliament") if (age >= 21 and age <= 60) else print("your are not eligible to be a member of parliament")

your are not eligible to be a member of parliament

In [ ]:
marks=int(input("enter your marks :"))
if (marks > 90) :
  print("A")
elif (marks <= 90 and marks >=80) :
  print("B")
elif (marks < 80 and marks >=70) :
  print("C")
elif (marks < 70 and marks >=60) :
  print("D")
elif (marks <60 and marks >=50) :
  print("E")
else:
    print("fail")

enter your marks :77
C

In [ ]:
num=int(input("enter a number:"))
print("even") if (num%2==0) else print ("odd")

enter a number:12
even

In [ ]:
num=int(input("enter a number :"))
a=num%3==0
b=num%5==0
if num % 3 == 0 and num % 5 == 0:
    print(f"{num} is divisible by both 3 and 5")
elif num % 3 == 0:
    print(f"{num} is divisible by 3 only")
elif num % 5 == 0:
    print(f"{num} is divisible by 5 only")
else:
  print(f"{num} is not divisible by 3 or 5")

enter a number :9
9 is divisible by 3 only

In [ ]:
name=input("enter name:")
age=int(input("enter age:"))
marks=int(input("enter your marks :"))
cnum=input("enter your contact number:")
if marks>60:
  print(f"{name} is eligible for exams")
else:
  print(f"{name} is not eligible for exams")

enter name:huj
enter age:22
enter your marks :66
enter your contact number:988675653
huj is eligible for exams

In [ ]:
""">40k titan
>32k elite
>25k select
<25k insider"""
purchase=int(input("enter your total purchase :"))
if (purchase >= 40000) :
  print("titan")
elif (purchase <40000 and purchase >=32000) :
  print("elite")
elif (purchase < 32000 and purchase >=25000) :
  print("select")
else:
  print("insider")

enter your total purchase :33333
elite

In [ ]:
num1 = float(input("Enter first number: "))
operator = input("Enter operator (+, -, *, /, %, **, //): ")
num2 = float(input("Enter second number: "))
if operator == "+":
    print(f"Result: {num1} + {num2} = {num1 + num2}")

elif operator == "-":
    print(f"Result: {num1} - {num2} = {num1 - num2}")

elif operator == "*":
    print(f"Result: {num1} * {num2} = {num1 * num2}")

elif operator == "/":
    if num2 == 0:
        print("Error: Division by zero is not allowed.")
    else:
        print(f"Result: {num1} / {num2} = {num1 / num2}")

elif operator == "%":
    if num2 == 0:
        print("Error: Cannot find remainder when dividing by zero.")
    else:
        print(f"Result: {num1} % {num2} = {num1 % num2}")

elif operator == "**":
    print(f"Result: {num1} ** {num2} = {num1 ** num2}")

elif operator == "//":
    if num2 == 0:
        print("Error: Floor division by zero is not allowed.")
    else:
        print(f"Result: {num1} // {num2} = {num1 // num2}")

else:
    print("Invalid operator! Please use +, -, *, /, %, **, or //.")

Enter first number: 12
Enter operator (+, -, *, /, %, **, //): +
Enter second number: 5
Result: 12.0 + 5.0 = 17.0

In [ ]:
balance = float(input("Enter starting balance: $"))
deduction = float(input("Enter amount to deduct: $"))
if deduction <= 0:
    print("Error: Deduction amount must be greater than 0.")

elif deduction > balance:
    print(f"Declined: Insufficient funds. (Balance: ${balance:.2f}, Attempted: ${deduction:.2f})")

else:
    balance -= deduction
    print(f"Success: ${deduction:.2f} deducted. New balance: ${balance:.2f}")

Enter starting balance: $12000
Enter amount to deduct: $1234
Success: $1234.00 deducted. New balance: $10766.00

In [ ]:
for i in range(10,-1,-1):
  print(f"hello world {i}")

hello world 10
hello world 9
hello world 8
hello world 7
hello world 6
hello world 5
hello world 4
hello world 3
hello world 2
hello world 1
hello world 0

In [ ]:
for i in range(10):
  if i == 6:
    break
  print(i)

0
1
2
3
4
5

In [ ]:
num = int(input("enter a number: "))
num = abs(num)
if 0 <= num <= 9:
    print(f"{num} is single digit")
elif 10 <= num <= 99:
    print(f"{num} is double digit")
elif 100 <= num <= 999:
    print(f"{num} is triple digit")
else:
    print(f"{num} is 4 or more digits (or out of bounds)")

enter a number: 466
466 is triple digit

In [ ]:
#most optimal
import math

num = int(input("enter a number: "))
num = abs(num)

# Special case: log10(0) is mathematically undefined, so we handle 0 manually
if num == 0:
    digit_count = 1
else:
    # Example: math.log10(150) is ~2.176 -> math.floor(2.176) is 2 -> 2 + 1 = 3 digits
    digit_count = math.floor(math.log10(num)) + 1

# Now we can dynamically label the digit type
if digit_count == 1:
    print(f"{num} is a single digit")
elif digit_count == 2:
    print(f"{num} is a double digit")
elif digit_count == 3:
    print(f"{num} is a triple digit")
else:
    print(f"{num} has {digit_count} digits")

enter a number: 12347899
12347899 has 8 digits

In [ ]:
import pandas as pd

df=pd.read_csv("/content/Zomato-data-.csv")
df.head(5) # Displays the first 5 rows of the DataFrame

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet

In [ ]:
df.shape
# Returns a tuple representing the dimensionality of the DataFrame (rows, columns)

(148, 7)

In [ ]:
df.dtypes
 # Returns a Series with the data type of each column

name                           object
online_order                   object
book_table                     object
rate                           object
votes                           int64
approx_cost(for two people)     int64
listed_in(type)                object
dtype: object

In [ ]:
df.sample(5)
# Displays a random sample of 5 rows from the DataFrame

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
32,Sweet Truth,Yes,No,3.9/5,35,500,Dining
134,Kaumudis Juoice,No,No,3.3/5,0,150,Dining
112,Just Bake,No,No,3.4/5,8,400,Dining
43,Domino's Pizza,Yes,No,3.9/5,540,800,Dining
85,The Big O Bakes,No,No,4.0/5,66,300,Dining

In [ ]:
df.columns
# Returns the column labels of the DataFrame

Index(['name', 'online_order', 'book_table', 'rate', 'votes',
       'approx_cost(for two people)', 'listed_in(type)'],
      dtype='object')

In [ ]:
df.info()
# Prints a concise summary of the DataFrame, including the index dtype and column dtypes, non-null values, and memory usage

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148 entries, 0 to 147
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         148 non-null    object
 1   online_order                 148 non-null    object
 2   book_table                   148 non-null    object
 3   rate                         148 non-null    object
 4   votes                        148 non-null    int64
 5   approx_cost(for two people)  148 non-null    int64
 6   listed_in(type)              148 non-null    object
dtypes: int64(2), object(5)
memory usage: 8.2+ KB

In [ ]:
df.describe()
# Generates descriptive statistics of the DataFrame's numerical columns

             votes  approx_cost(for two people)
count   148.000000                   148.000000
mean    264.810811                   418.243243
std     653.676951                   223.085098
min       0.000000                   100.000000
25%       6.750000                   200.000000
50%      43.500000                   400.000000
75%     221.750000                   600.000000
max    4884.000000                   950.000000

In [ ]:
df[["name","online_order"]]
# Selects and displays multiple specific columns from the DataFrame

                      name online_order
0                    Jalsa          Yes
1           Spice Elephant          Yes
2          San Churro Cafe          Yes
3    Addhuri Udupi Bhojana           No
4            Grand Village           No
..                     ...          ...
143       Melting Melodies           No
144        New Indraprasta           No
145           Anna Kuteera          Yes
146                 Darbar           No
147          Vijayalakshmi          Yes

[148 rows x 2 columns]

In [ ]:
df[["name"]]
# Selects and displays a single specific column from the DataFrame, returning a DataFrame

                      name
0                    Jalsa
1           Spice Elephant
2          San Churro Cafe
3    Addhuri Udupi Bhojana
4            Grand Village
..                     ...
143       Melting Melodies
144        New Indraprasta
145           Anna Kuteera
146                 Darbar
147          Vijayalakshmi

[148 rows x 1 columns]

In [ ]:
df[df["rate"] > "3.8"]
# Filters the DataFrame to show rows where the 'rate' column value is greater than '3.8' (string comparison here)
#(wrong approach) used string comparison as data in "rate" is string
#convert data of rate columns to int then do it

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet
5,Timepass Dinner,Yes,No,3.8/5,286,600,Buffet
...,...,...,...,...,...,...,...
103,Floured-Baked With Love,No,No,3.8 /5,45,400,Dining
120,Bengaluru Coffee House,Yes,No,4.1/5,201,300,Dining
133,Swathi Cool Point,No,No,4.1/5,0,200,Dining
145,Anna Kuteera,Yes,No,4.0/5,771,450,Dining
147,Vijayalakshmi,Yes,No,3.9/5,47,200,Dining

In [ ]:
df[(df["listed_in(type)"] == "Dining") & (df["votes"] > 700 )]
# Filters the DataFrame based on multiple conditions: 'listed_in(type)' is 'Dining' AND 'votes' is greater than 700

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
37,Szechuan Dragon,Yes,No,4.2/5,1647,600,Dining
47,Recipe,Yes,No,4.0/5,804,450,Dining
54,Roving Feast,No,No,4.0/5,1047,450,Dining
63,Jeet Restaurant,No,Yes,4.0/5,808,850,Dining
65,Kabab Magic,Yes,No,4.1/5,1720,400,Dining
67,Gustoes Beer House,No,No,4.1/5,868,700,Dining
86,Meghana Foods,Yes,No,4.4/5,4401,600,Dining
145,Anna Kuteera,Yes,No,4.0/5,771,450,Dining

In [ ]:
df.sort_values("votes") #by default ascending

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
110,Hari Super Sandwich,No,No,3.2/5,0,200,Dining
107,Coffee Shopee,No,No,3.4/5,0,250,Dining
117,Kulfi & More,No,No,3.4/5,0,150,Dining
118,Kannadigas Karavali,No,No,3.4/5,0,250,Dining
116,Wood Stove,No,No,3.4/5,0,150,Dining
...,...,...,...,...,...,...,...
65,Kabab Magic,Yes,No,4.1/5,1720,400,Dining
44,Onesta,Yes,Yes,4.6/5,2556,600,other
7,Onesta,Yes,Yes,4.6/5,2556,600,Cafes
86,Meghana Foods,Yes,No,4.4/5,4401,600,Dining
38,Empire Restaurant,Yes,No,4.4/5,4884,750,other

In [ ]:
df.sort_values("votes", ascending = False) #descending order

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
38,Empire Restaurant,Yes,No,4.4/5,4884,750,other
86,Meghana Foods,Yes,No,4.4/5,4401,600,Dining
7,Onesta,Yes,Yes,4.6/5,2556,600,Cafes
44,Onesta,Yes,Yes,4.6/5,2556,600,other
65,Kabab Magic,Yes,No,4.1/5,1720,400,Dining
...,...,...,...,...,...,...,...
140,Darkolates,No,No,3.3/5,0,200,Dining
143,Melting Melodies,No,No,3.3/5,0,100,Dining
142,Gawdaru Mane Beriyani,No,No,3.3/5,0,300,Dining
141,Swaada Healthy Kitchen,No,No,3.3/5,0,350,Dining
144,New Indraprasta,No,No,3.3/5,0,150,Dining

In [ ]:
df.rename(columns= {"name":"customer_name"} , inplace=True)
# Renames the 'name' column to 'customer_name' in the DataFrame.
#inplace=True` modifies the DataFrame directly, without returning a new one.

In [ ]:
df.isnull().sum()
# `isnull()` detects missing values and `sum()` counts them per column.

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
approx_cost(for two people)    0
listed_in(type)                0
dtype: int64

In [ ]:
#df['rate'] = pd.to_numeric(df["rate"])
# (wrong because the 'rate' column contains strings like '4.1/5'.
# need to clean these strings before converting them to a numeric type )

# Cleans the 'rate' column by removing '/5' and converts it to a float type.
df['rate'] = df['rate'].str.replace('/5', '', regex=False).astype(float)
df.head()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1,775,800,Buffet
1,Spice Elephant,Yes,No,4.1,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7,88,300,Buffet
4,Grand Village,No,No,3.8,166,600,Buffet